---
- name: Update all packages and reboot if needed
  hosts: all
  become: true
  tasks:

    - name: Gather facts (including ansible_os_family)
      ansible.builtin.setup:

    - name: Update all packages (RedHat-based)
      ansible.builtin.yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Update all packages (Debian-based)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (Debian-based)
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required (RHEL-based)
      ansible.builtin.command: needs-restarting -r
      register: needs_reboot
      failed_when: false
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Reboot if needed (Debian-based)
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: ansible_os_family == "Debian" and reboot_required_file.stat.exists

    - name: Reboot if needed (RedHat-based)
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: ansible_os_family == "RedHat" and needs_reboot.rc == 1
