---
- name: Update all running Docker containers
  hosts: all
  become: true
  tasks:

    - name: Get list of running container names
      ansible.builtin.command: docker ps --format '{{ "{{.Names}}" }}'
      register: running_containers

    - name: Pull latest images for running containers
      ansible.builtin.shell: |
        docker pull "$(docker inspect --format='{{"{{.Config.Image}}"}}' {{ item }})"
      loop: "{{ running_containers.stdout_lines }}"
      when: running_containers.stdout_lines | length > 0

    - name: Restart running containers to apply updates
      ansible.builtin.shell: docker restart {{ item }}
      loop: "{{ running_containers.stdout_lines }}"
      when: running_containers.stdout_lines | length > 0
